apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: other
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: other
    newName: rg.fr-par.scw.cloud/djnd/other
    newTag: "latest"